sudo: required

language: generic

env:
  global:
    - IMAGE=lorf/csr-spi-ftdi-build:ubuntu-16.04-i386

services:
  - docker

branches:
  only:
    - master

before_script:
  - docker pull "$IMAGE" || true

script:
  - docker build --pull --cache-from "$IMAGE" -t "$IMAGE" .

after_script:
  - docker images

before_deploy:
  - ./docker-login.sh

deploy:
  provider: script
  script: docker push "$IMAGE"
  on:
    all_branches: true

notifications:
  email:
    recipients:
      - $EMAIL
    on_success: never
    on_failure: always
